[package]
name = "curious-enigma"
version = "0.2.0"
authors = ["Drew Christensen <emoryandrewchristensen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-postgres = "0.7.1"

[[bin]]
name = "curious-enigma"
path = "src/main.rs"
