[package]
name = "curious-enigma"
version = "0.3.0"
authors = ["Drew Christensen <emoryandrewchristensen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
actix-files = "0.5.0"
futures = "0.3.14"
sqlx = { version = "0.5.1", features = [ "runtime-actix-native-tls", "postgres" ] }
chrono = "0.4.19"
bcrypt = "0.8.2"

[[bin]]
name = "curious-enigma"
path = "src/main.rs"
