[package]
name = "curious-enigma"
version = "0.3.0"
authors = ["Drew Christensen <emoryandrewchristensen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-http = "2.2.0"
actix-web = "3.3.2"
actix-files = "0.5.0"
actix-service = "1.0.6"
sqlx = { version = "0.5.1", features = [ "runtime-actix-native-tls", "postgres", "chrono", "macros", "serde" ] }
serde = "1.0.125"
chrono = "0.4.19"
# futures = "0.3.14"
# bcrypt = "0.8.2"

[[bin]]
name = "curious-enigma"
path = "src/main.rs"
