CREATE TABLE IF NOT EXISTS sessions (
	id VARCHAR NOT NULL PRIMARY KEY,
	expires TIMESTAMP NULL,
	session TEXT NOT NULL
);

DO $$ BEGIN
	CREATE TYPE USER_ROLE AS ENUM ('user', 'admin');
EXCEPTION
	WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(64) NOT NULL UNIQUE,
	email VARCHAR(128) NOT NULL UNIQUE,
	hash VARCHAR(128) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	role USER_ROLE NOT NULL DEFAULT 'user'
);