CREATE TYPE ROLE AS ENUM ('user', 'admin');
CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(64) NOT NULL UNIQUE,
	email VARCHAR(128) NOT NULL UNIQUE,
	hash VARCHAR(128) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	role ROLE NOT NULL DEFAULT 'user'
);